# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Backdoor
      run: cd backdoor/cmd/ && CGO_ENABLED=0 go build -v

    #- name: Test backdoor help menu
    #  run: backdoor/cmd/cmd -h

    - name: Build Shodan
      run: cd httpRequests/cmd/shodan/ && CGO_ENABLED=0 go build -v

    # - name: Test Shodan help menu
    #   run: httpRequests/cmd/shodan/shodan -h
