# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Backdoor
      run: cd backdoor/cmd/ && CGO_ENABLED=0 go build -v

    #- name: Test backdoor help menu
    #  run: backdoor/cmd/cmd -h

    - name: Build backdoor
      run: cd backdoor/cmd && CGO_ENABLED=0 go build -v

    - name: Build Shodan
      run: cd httpRequests/cmd/shodan/ && CGO_ENABLED=0 go build -v

    - name: Build Metasploit
      run: cd metasploit-minimal/client && CGO_ENABLED=0 go build -v

    - name: Build Credential Harvester
      run: cd credentialharvest/ && CGO_ENABLED=0 go build -v

    - name: Build Bing dork Scraper
      run: cd scraper/bing/cmd && CGO_ENABLED=0 go build -v

    - name: Build Server Template 
      run: cd server/cmd && CGO_ENABLED=0 go build -v

    - name: Build Keylogger
      run: cd keylogger/cmd && CGO_ENABLED=0 go build -v

    - name: Build Scraper
      run: cd scraper/bing/cmd && CGO_ENABLED=0 go build -v

    - name: Build multiplexer
      run: cd multiplexing-command-control/cmd && CGO_ENABLED=0 go build -v